### ISSUE TITLE
Actions fails queitly when permissions associated with the token are invalid

### ISSUE THREAD

**Issue by tovbinm** [buildkite/trigger-pipeline-action#23]
We created a token with `write_builds` permission, but the actions kept failing silently and it was difficult to troubleshoot why.

We ended up providing `Organization Access` which resolved the issue.

**Comment by EnricoMi** [comment]
@tovbinm this has just been merged to master. @lizrabuya when is the next release scheduled?

**Comment by lizrabuya** [comment]
@EnricoMi  @jeremy  @tovbinm  hey folks! Just letting you know that we have released v1.3.0

**Comment by EnricoMi** [comment]
awesome, thanks!
