### ISSUE TITLE
Document how to run test/entrypoint.bats

### ISSUE THREAD

**Issue by jlisee** [buildkite/trigger-pipeline-action#7]
There is a useful looking test script in `test/entrypoint.bats` can you document how to run it?  I have found the `bats-core`, `bats-support` and `bats-assert` projects but a quick walkthrough on how to set them up would be help a lot.

**Comment by lizrabuya** [comment]
hi @jlisee , just letting you know we have updated our docs with the instructions on running the test scripts locally.
